config/routes.rb
Blog::Application.routes.draw do
  match 'posts/:id' => 'posts#show', :as => :posts_show
  
  match "posts" => "posts#index", :as => :posts_index
  
  match "post/new" => "posts#new", :as => :posts_new
  match "post/create" => "posts#create", :as => :posts_create
  
  match "posts/:id/edit" => "posts#edit", :as => :posts_edit
  match "posts/:id/update" => "posts#update", :as => :posts_update

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :post_id, :user_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :encrypted_password, :is_admin, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.find(:all)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @post.save
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:post][:id])
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @post.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<p>Current time is <%= Time.now %></p>
</body>
</html>

app/views/posts/create.html.erb
<h1>Thank you for your post</h1>
<%= link_to "Back to Index", posts_show_path('') %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @post, :url => { :action => "update" } do |f| %>  
  <%= f.label :title, "Title" %><br />
  <%= f.text_field :title, :value => @post.title %><br />
  <%= f.label :body, "Body", :value => @post.body %><br />
  <%= f.text_area :body, :size => "60x12" %><br />
  <%= f.hidden_field :id, :value => @post.id %>
  <%= f.submit "Submit" %>
<% end %>

app/views/posts/index.html.erb
<h1>My Blog Posts</h1>
<% unless @posts.empty? %>
  <ul>
  <% for post in @posts %>
     <li><%= link_to post.title, posts_show_path(post.id) %></li>
  <% end %>
  </ul>
<% else %>
  <p>There are no posts here!</p>
<% end %>
<%= link_to 'Create new post', posts_new_path %>

app/views/posts/new.html.erb
<%= form_for @post, :url => { :action => "create" } do |f| %>  
  <%= f.label :title, "Title" %><br />
  <%= f.text_field :title %><br />
  <%= f.label :body, "Body" %><br />
  <%= f.text_area :body, :size => "60x12" %><br />
  <%= f.submit "Submit" %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<div class="blog_post">
  <%= @post.body %>
</div>
<p><%= link_to "Edit Post", posts_edit_path(@post.id) %></p>
<p><%= link_to "Back to Index", posts_show_path('') %></p>

app/views/posts/update.html.erb
<h1>Your post has been updated</h1>
<p><%= link_to "View your post", posts_show_path(@post.id) %></p>